# Number of digits in serial.
NumSerialDigits = 12
# Number of digts to generate for the key.
NumKeyDigits = 6
# Number of seconds between each server serial generation.
ServerSerialRefreshSeconds = 60